common_prompts = {
    1: 'a sailboat floating on calm water',
    2: 'a pine tree on a small hill',
    3: 'a cat sitting inside a teacup',
    4: 'a hot air balloon high over mountains',
    5: 'a dragon flying in the sky, full body',
    6: 'a bicycle leaning against a brick wall',
    7: 'a small house with two windows',
    8: 'a fruit basket with fruits',
    9: 'a portrait of naruto',
    10: 'enchanted forest with glowing mushrooms',
    11: 'James Bond in a tuxedo and holding a gun',
    12: 'a man performing tai chi',
    13: 'a butterfly with plain wings',
    14: 'a campfire under starry sky',
    15: 'sydney opera house',
    16: 'a bridge over a narrow river',
    17: 'a robot holding a flower',
    18: 'two white bunnies',
    19: 'a lighthouse by the ocean',
    20: 'an owl perched on a car',
    21: 'a single feather falling through air',
    22: 'a pair of glasses on an open book',
    23: 'a steaming coffee cup on a saucer',
    24: 'a crescent moon with one star',
    25: 'a fox standing on a log',
    26: 'an empty swing hanging from a tree',
    27: 'a vintage camera on a tripod',
    28: 'a seashell on smooth sand',
    29: 'a paper airplane mid-flight',
    30: 'a single rose in a slim vase',
    31: 'a mountain peak piercing clouds',
    32: 'a deer standing in a meadow',
    33: 'a hanging lantern at night',
    34: 'a winding road through a desert',
    35: 'a penguin on an ice floe',
    36: 'a key lying on a wooden table',
    37: 'a waterfall cascading down rocks',
    38: 'a pair of scissors cutting paper',
    39: 'a street lamp in light fog',
    40: 'a cactus in a clay pot',
    41: 'a violin leaning on a chair',
    42: 'a squirrel holding an acorn',
    43: 'a single leaf floating on water',
    44: 'an open umbrella against wind',
    45: 'a stone arch bridge at dawn',
    46: 'a chess piece on a board',
    47: 'a crow perched on a fence',
    48: 'a winding staircase in a tower',
    49: 'a person doing yoga pose',
    50: 'a winding river through hills'
}


sketchy_prompts = {
    1: "a pig", 
    2: "a spoon", 
    3: "a bat", 
    4: "a flower", 
    5: "a hotdog",
    6: "an umbrella", 
    7: "a raccoon", 
    8: "a skyscraper", 
    9: "a hat", 
    10: "a rhinoceros",
    11: "a flower", 
    12: "a mouse", 
    13: "a door", 
    14: "an elephant", 
    15: "eyeglasses",
    16: "a harp", 
    17: "a bee", 
    18: "a teddy bear", 
    19: "a racket", 
    20: "a couch",
    21: "an ape", 
    22: "a violin", 
    23: "a sheep", 
    24: "a songbird", 
    25: "a scorpion",
    26: "a pear", 
    27: "a chair", 
    28: "a skyscraper", 
    29: "a shark", 
    30: "a violin",
    31: "a crab", 
    32: "a hamburger", 
    33: "a flower", 
    34: "an hourglass", 
    35: "a pistol",
    36: "a lion", 
    37: "a hat", 
    38: "a hamburger", 
    39: "a saxophone", 
    40: "a raccoon",
    41: "a mouse", 
    42: "a piano", 
    43: "a fan", 
    44: "a chicken", 
    45: "a piano",
    46: "a crocodilian", 
    47: "a lizard", 
    48: "a pickup truck", 
    49: "a hotdog", 
    50: "a fish"
}